@startuml

class RootBeanDefinition
interface AnnotatedBeanDefinition

class ConfigurationClassBeanDefinition
ConfigurationClassBeanDefinition --|> AnnotatedBeanDefinition
ConfigurationClassBeanDefinition --|> RootBeanDefinition

class ClassDerivedBeanDefinition
ClassDerivedBeanDefinition --|> RootBeanDefinition

@enduml